image:
  repository: justingav/discord-bot
  tag: latest
  pullPolicy: Always

commandPrefix: "!"
logLevel: "INFO"

keycloak:
  url: "https://keycloak"
  realm: "BB"
  discordClientId: "discord-to-user"

supabase:
  url: "http://supabase:8000"

insecure: true

services:
  userService: "http://user-service"
  paymentService: "http://payment-service"
  itemService: "http://item-service"

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
