-- User Service Database Functions
-- Run this script in your Supabase SQL Editor to create all required functions

-- ============================================================================
-- Table: Users
-- ============================================================================
CREATE TABLE IF NOT EXISTS public."Users" (
  card_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name text NOT NULL DEFAULT ''::text,
  balance bigint NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  last_name text NOT NULL DEFAULT ''::text,
  CONSTRAINT users_pkey PRIMARY KEY (card_id)
) TABLESPACE pg_default;

-- ============================================================================
-- Function: create_user
-- Creates a new user with the provided card ID
-- ============================================================================
CREATE OR REPLACE FUNCTION public.create_user(
  card_id_input bigint,
  first_name_input text,
  last_name_input text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public."Users" (card_id, first_name, last_name, balance, active)
  VALUES (card_id_input, first_name_input, last_name_input, 0, TRUE);
END;
$$;

-- ============================================================================
-- Function: fetch_user_info
-- Retrieves user information by card ID
-- ============================================================================
CREATE OR REPLACE FUNCTION public.fetch_user_info(
  user_id_input bigint
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    'active', active,
    'first_name', first_name,
    'last_name', last_name,
    'balance', balance
  ) INTO result
  FROM public."Users"
  WHERE card_id = user_id_input;

  IF result IS NULL THEN
    RAISE EXCEPTION 'User not found';
  END IF;

  RETURN result;
END;
$$;

-- ============================================================================
-- Function: user_status
-- Updates a user's active status
-- ============================================================================
CREATE OR REPLACE FUNCTION public.user_status(
  user_id_input bigint,
  user_status_input boolean
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  current_status BOOLEAN;
BEGIN
  SELECT active INTO current_status
  FROM public."Users"
  WHERE card_id = user_id_input
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'User not found';
  END IF;

  IF current_status = user_status_input THEN
    RAISE EXCEPTION 'User status is already active=%', current_status;
  END IF;

  UPDATE public."Users"
  SET active = user_status_input
  WHERE card_id = user_id_input;

  RETURN 'User with id ' || user_id_input || ' has new status active = ' || user_status_input;
END;
$$;

-- ============================================================================
-- Function: add_balance
-- Adds balance to a user's account and records the transaction
-- ============================================================================
CREATE OR REPLACE FUNCTION public.add_balance(
  user_id_input bigint,
  balance_input bigint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  current_balance bigint;
  new_balance bigint;
BEGIN
  -- Find and Lock the User to prevent race conditions
  SELECT balance INTO current_balance
  FROM public."Users"
  WHERE card_id = user_id_input
  FOR UPDATE;

  -- Run Payment Logic Checks
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User not found';
  END IF;

  -- Create the Ledger Record (optional - comment out if Transaction_History table doesn't exist)
  -- INSERT INTO public."Transaction_History" (user_id, item, amount_delta)
  -- VALUES (user_id_input, NULL, balance_input);

  -- Update the User's Balance
  UPDATE public."Users"
  SET balance = current_balance + balance_input
  WHERE card_id = user_id_input
  RETURNING balance INTO new_balance;
  
  -- Return the Result
  RETURN new_balance;
END;
$$;

-- ============================================================================
-- Grant permissions for Supabase anonymous/authenticated roles
-- ============================================================================
GRANT EXECUTE ON FUNCTION public.create_user(bigint, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fetch_user_info(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_status(bigint, boolean) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_balance(bigint, bigint) TO anon, authenticated, service_role;
