apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.itemService.name }}
spec:
  {{- if not .Values.itemService.autoscaling.enabled }}
  replicas: {{ .Values.itemService.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.itemService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.itemService.name }}
    spec:
      containers:
      - name: item-service
        image: {{ .Values.itemService.image }}:{{ .Values.itemService.tag }}
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: {{ .Values.itemService.resources.requests.memory | default "60Mi" }}
            cpu: {{ .Values.itemService.resources.requests.cpu | default "4m" }}
          limits:
            memory: {{ .Values.itemService.resources.limits.memory | default "120Mi" }}
            cpu: {{ .Values.itemService.resources.limits.cpu | default "10m" }}
        env:
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: supabase-secret
                key: SUPABASE_URL
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: supabase-secret
                key: SUPABASE_KEY
          - name: KEYCLOAK_URL
            value: '{{ .Values.itemService.keycloakUrl | default "http://keycloak:8080" }}'
          - name: KEYCLOAK_REALM
            value: '{{ .Values.itemService.keycloakRealm | default "BB" }}'
          - name: KEYCLOAK_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_ADMIN_USER
          - name: KEYCLOAK_ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_ADMIN_PASS
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_CLIENT_ID
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_CLIENT_SECRET
          - name: KEYCLOAK_CALLBACK_URI
            value: "http://item-service:8004/callback"
          - name: INSECURE
            value: '{{ .Values.itemService.insecure | default "false" }}'
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
