apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  username: {{ .Values.keycloak.database.username }}
  password: {{ .Values.keycloak.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  username: {{ .Values.keycloak.adminUser }}
  password: {{ .Values.keycloak.adminPassword }}